name = "KerbalRemoteLogging"
uuid = "032c5fe9-e08c-423e-8a23-833859907386"
authors = ["Rhahi <git@rhahi.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
